server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
spring:
  application:
    name: audit-system
  datasource:
    password: aiya123
    url: jdbc:mysql://localhost:3306/mynews?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jackson:
    time-zone: Asia/Shanghai
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    banner: false
